package entities;
// Generated May 28, 2022, 3:41:14 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Aircraft generated by hbm2java
 */
@Entity
@Table(name = "aircraft", catalog = "flightticketmanagementdatabase")
public class Aircraft implements java.io.Serializable {

	private String aircraftId;
	private Integer numberOfSeats;
	private Set<Flight> flights = new HashSet<Flight>(0);

	public Aircraft() {
	}

	public Aircraft(String aircraftId) {
		this.aircraftId = aircraftId;
	}

	public Aircraft(String aircraftId, Integer numberOfSeats, Set<Flight> flights) {
		this.aircraftId = aircraftId;
		this.numberOfSeats = numberOfSeats;
		this.flights = flights;
	}

	@Id

	@Column(name = "Aircraft_ID", unique = true, nullable = false, length = 20)
	public String getAircraftId() {
		return this.aircraftId;
	}

	public void setAircraftId(String aircraftId) {
		this.aircraftId = aircraftId;
	}

	@Column(name = "NumberOfSeats")
	public Integer getNumberOfSeats() {
		return this.numberOfSeats;
	}

	public void setNumberOfSeats(Integer numberOfSeats) {
		this.numberOfSeats = numberOfSeats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aircraft")
	public Set<Flight> getFlights() {
		return this.flights;
	}

	public void setFlights(Set<Flight> flights) {
		this.flights = flights;
	}

}
