package entities;
// Generated Jun 1, 2022, 11:56:14 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Airport generated by hbm2java
 */
@Entity
@Table(name = "airport", catalog = "flightticketmanagementdatabase")
public class Airport implements java.io.Serializable {

	private String departureId;
	private String airportName;
	private String cityProvince;
	private Set<Flight> flightsForDestinationId = new HashSet<Flight>(0);
	private Set<Flight> flightsForDepartureId = new HashSet<Flight>(0);

	public Airport() {
	}

	public Airport(String departureId) {
		this.departureId = departureId;
	}

	public Airport(String departureId, String airportName, String cityProvince, Set<Flight> flightsForDestinationId,
			Set<Flight> flightsForDepartureId) {
		this.departureId = departureId;
		this.airportName = airportName;
		this.cityProvince = cityProvince;
		this.flightsForDestinationId = flightsForDestinationId;
		this.flightsForDepartureId = flightsForDepartureId;
	}

	@Id

	@Column(name = "Departure_ID", unique = true, nullable = false, length = 10)
	public String getDepartureId() {
		return this.departureId;
	}

	public void setDepartureId(String departureId) {
		this.departureId = departureId;
	}

	@Column(name = "AirportName", length = 100)
	public String getAirportName() {
		return this.airportName;
	}

	public void setAirportName(String airportName) {
		this.airportName = airportName;
	}

	@Column(name = "City_Province", length = 100)
	public String getCityProvince() {
		return this.cityProvince;
	}

	public void setCityProvince(String cityProvince) {
		this.cityProvince = cityProvince;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "airportByDestinationId")
	public Set<Flight> getFlightsForDestinationId() {
		return this.flightsForDestinationId;
	}

	public void setFlightsForDestinationId(Set<Flight> flightsForDestinationId) {
		this.flightsForDestinationId = flightsForDestinationId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "airportByDepartureId")
	public Set<Flight> getFlightsForDepartureId() {
		return this.flightsForDepartureId;
	}

	public void setFlightsForDepartureId(Set<Flight> flightsForDepartureId) {
		this.flightsForDepartureId = flightsForDepartureId;
	}

}
