package entities;
// Generated May 25, 2022, 10:24:12 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Airport generated by hbm2java
 */
@Entity
@Table(name = "airport", catalog = "flightticketmanagementdatabase")
public class Airport implements java.io.Serializable {

	private String departureId;
	private String airportName;
	private String cityProvince;
	private Set<Flight> flights = new HashSet<Flight>(0);

	public Airport() {
	}

	public Airport(String departureId) {
		this.departureId = departureId;
	}

	public Airport(String departureId, String airportName, String cityProvince, Set<Flight> flights) {
		this.departureId = departureId;
		this.airportName = airportName;
		this.cityProvince = cityProvince;
		this.flights = flights;
	}

	@Id

	@Column(name = "Departure_ID", unique = true, nullable = false, length = 10)
	public String getDepartureId() {
		return this.departureId;
	}

	public void setDepartureId(String departureId) {
		this.departureId = departureId;
	}

	@Column(name = "AirportName", length = 100)
	public String getAirportName() {
		return this.airportName;
	}

	public void setAirportName(String airportName) {
		this.airportName = airportName;
	}

	@Column(name = "City_Province", length = 100)
	public String getCityProvince() {
		return this.cityProvince;
	}

	public void setCityProvince(String cityProvince) {
		this.cityProvince = cityProvince;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "airport")
	public Set<Flight> getFlights() {
		return this.flights;
	}

	public void setFlights(Set<Flight> flights) {
		this.flights = flights;
	}

}
