package entities;
// Generated Jun 6, 2022, 6:02:59 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Flight generated by hbm2java
 */
@Entity
@Table(name = "flight", catalog = "sellticketdb")
public class Flight implements java.io.Serializable {

	private String flightId;
	private Aircraft aircraft;
	private Airport airportByDepartureId;
	private Airport airportByDestinationId;
	private String takeOffTime;
	private String landingTime;
	private Date flightDate;
	private Integer numberOfEconomySeats;
	private Integer numberOfBusinessSeats;
	private String status;
	private String basicPrice;
	private Integer isActive;
	private Set<Ticket> tickets = new HashSet<Ticket>(0);

	public Flight() {
	}

	public Flight(String flightId, Aircraft aircraft, Airport airportByDepartureId) {
		this.flightId = flightId;
		this.aircraft = aircraft;
		this.airportByDepartureId = airportByDepartureId;
	}

	public Flight(String flightId, Aircraft aircraft, Airport airportByDepartureId, Airport airportByDestinationId,
			String takeOffTime, String landingTime, Date flightDate, Integer numberOfEconomySeats,
			Integer numberOfBusinessSeats, String status, String basicPrice, Integer isActive, Set<Ticket> tickets) {
		this.flightId = flightId;
		this.aircraft = aircraft;
		this.airportByDepartureId = airportByDepartureId;
		this.airportByDestinationId = airportByDestinationId;
		this.takeOffTime = takeOffTime;
		this.landingTime = landingTime;
		this.flightDate = flightDate;
		this.numberOfEconomySeats = numberOfEconomySeats;
		this.numberOfBusinessSeats = numberOfBusinessSeats;
		this.status = status;
		this.basicPrice = basicPrice;
		this.isActive = isActive;
		this.tickets = tickets;
	}

	@Id

	@Column(name = "Flight_ID", unique = true, nullable = false, length = 10)
	public String getFlightId() {
		return this.flightId;
	}

	public void setFlightId(String flightId) {
		this.flightId = flightId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Aircraft_ID", nullable = false)
	public Aircraft getAircraft() {
		return this.aircraft;
	}

	public void setAircraft(Aircraft aircraft) {
		this.aircraft = aircraft;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Departure_ID", nullable = false)
	public Airport getAirportByDepartureId() {
		return this.airportByDepartureId;
	}

	public void setAirportByDepartureId(Airport airportByDepartureId) {
		this.airportByDepartureId = airportByDepartureId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Destination_ID")
	public Airport getAirportByDestinationId() {
		return this.airportByDestinationId;
	}

	public void setAirportByDestinationId(Airport airportByDestinationId) {
		this.airportByDestinationId = airportByDestinationId;
	}

	@Column(name = "TakeOffTime", length = 8)
	public String getTakeOffTime() {
		return this.takeOffTime;
	}

	public void setTakeOffTime(String takeOffTime) {
		this.takeOffTime = takeOffTime;
	}

	@Column(name = "LandingTime", length = 8)
	public String getLandingTime() {
		return this.landingTime;
	}

	public void setLandingTime(String landingTime) {
		this.landingTime = landingTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FlightDate", length = 10)
	public Date getFlightDate() {
		return this.flightDate;
	}

	public void setFlightDate(Date flightDate) {
		this.flightDate = flightDate;
	}

	@Column(name = "NumberOfEconomySeats")
	public Integer getNumberOfEconomySeats() {
		return this.numberOfEconomySeats;
	}

	public void setNumberOfEconomySeats(Integer numberOfEconomySeats) {
		this.numberOfEconomySeats = numberOfEconomySeats;
	}

	@Column(name = "NumberOfBusinessSeats")
	public Integer getNumberOfBusinessSeats() {
		return this.numberOfBusinessSeats;
	}

	public void setNumberOfBusinessSeats(Integer numberOfBusinessSeats) {
		this.numberOfBusinessSeats = numberOfBusinessSeats;
	}

	@Column(name = "Status", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "BasicPrice", length = 16777215)
	public String getBasicPrice() {
		return this.basicPrice;
	}

	public void setBasicPrice(String basicPrice) {
		this.basicPrice = basicPrice;
	}

	@Column(name = "isActive")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flight")
	public Set<Ticket> getTickets() {
		return this.tickets;
	}

	public void setTickets(Set<Ticket> tickets) {
		this.tickets = tickets;
	}

	public void decreaseBCNumber() {
		this.numberOfBusinessSeats--;
	}
	
	public void decreaseECNumber() {
		this.numberOfEconomySeats--;
	}
	
	public void ascendingBCNumber() {
		this.numberOfBusinessSeats++;
	}
	
	public void ascendingECNumber() {
		this.numberOfEconomySeats++;
	}
}
