package entities;
// Generated Jun 6, 2022, 6:02:59 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name = "ticket", catalog = "sellticketdb")
public class Ticket implements java.io.Serializable {

	private Integer ticketId;
	private Customer customer;
	private Employee employee;
	private Flight flight;
	private Ticketclass ticketclass;
	private String ticketType;
	private String passengerName;
	private Set<Invoice> invoices = new HashSet<Invoice>(0);

	public Ticket() {
	}

	public Ticket(Customer customer, Employee employee, Flight flight, Ticketclass ticketclass) {
		this.customer = customer;
		this.employee = employee;
		this.flight = flight;
		this.ticketclass = ticketclass;
	}

	public Ticket(Customer customer, Employee employee, Flight flight, Ticketclass ticketclass, String ticketType,
			String passengerName, Set<Invoice> invoices) {
		this.customer = customer;
		this.employee = employee;
		this.flight = flight;
		this.ticketclass = ticketclass;
		this.ticketType = ticketType;
		this.passengerName = passengerName;
		this.invoices = invoices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Ticket_ID", unique = true, nullable = false)
	public Integer getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(Integer ticketId) {
		this.ticketId = ticketId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Customer_ID", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Employee_ID", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Flight_ID", nullable = false)
	public Flight getFlight() {
		return this.flight;
	}

	public void setFlight(Flight flight) {
		this.flight = flight;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TicketClass_ID", nullable = false)
	public Ticketclass getTicketclass() {
		return this.ticketclass;
	}

	public void setTicketclass(Ticketclass ticketclass) {
		this.ticketclass = ticketclass;
	}

	@Column(name = "TicketType", length = 100)
	public String getTicketType() {
		return this.ticketType;
	}

	public void setTicketType(String ticketType) {
		this.ticketType = ticketType;
	}

	@Column(name = "PassengerName", length = 100)
	public String getPassengerName() {
		return this.passengerName;
	}

	public void setPassengerName(String passengerName) {
		this.passengerName = passengerName;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "ticket", cascade = CascadeType.ALL)
	public Set<Invoice> getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set<Invoice> invoices) {
		this.invoices = invoices;
	}

}
